version: "3"

tasks:
  deploy-staging-cluster:
    desc: "Deploy argocd gitops staging target"
    cmds:
      - kubectl apply -f ../../../../k8s/namespaces/argocd.yaml
      - kubectl apply -f ../../../../k8s/namespaces/staging.yaml
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl apply -f staging/application.yaml

  deploy-production-cluster:
    desc: "Deploy argocd gitops production target"
    cmds:
      - kubectl apply -f ../../../../k8s/namespaces/argocd.yaml
      - kubectl apply -f ../../../../k8s/namespaces/production.yaml
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl apply -f production/application.yaml
      
  delete-staging-cluster:
    desc: "Deploy argocd gitops staging target"
    cmds:
      - kubectl delete -f staging/application.yaml
      - kubectl delete -f ../../../../k8s/namespaces/argocd.yaml
      - kubectl delete -f ../../../../k8s/namespaces/staging.yaml

  delete-production-cluster:
    desc: "Deploy argocd gitops production target"
    cmds:
      - kubectl delete -f production/application.yaml
      - kubectl delete -f ../../../../k8s/namespaces/argocd.yaml
      - kubectl delete -f ../../../../k8s/namespaces/production.yaml
