version: "3"

includes:
  github-actions:
    taskfile: ./github-actions/Taskfile.yaml
    dir: ./github-actions

  kluctl-gitops:
    taskfile: ./argocd-gitops/Taskfile.yaml
    dir: ./argocd-gitops
