version: "3"

tasks:
  00-deploy-monitoring:
    desc: "Deploy argocd gitops staging target"
    cmds:
      - kubectl apply -n monitoring -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl apply -f application.yaml

  01-port-forward-webui:
    desc: "Port forward web UI to localhost on port 8080"
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443
